name: CI
on:
  - push
  - pull_request
jobs:
  ci:
    name: Tests and Build Check on Node 15
    runs-on: ubuntu-20.04
    steps:
      # checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Setup NodeJS
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15

      # Install packages
      - name: Install NPM Packages
        run: npm ci --ignore-scripts

      # Lint
      - name: Run Linting
        run: npm run lint

      # Formatting
      - name: Run Formatting
        run: npm run format

      # Tests
      - name: Run Jest Tests
        run: npm run test:ci
        env:
          CI: true

      - name: Build
        run: npm run build:ci
